### ISSUE TITLE
We can use setlocale to better support search for Unicode

### ISSUE THREAD

**Issue by stonedreamforest** [horsicq/stringsx64dbg#1]
such as :
- setlocale(LC_ALL , "zh-cn");
- setlocale(LC_ALL , "pt-BR");

...

#### Reference：
[language-strings](https://docs.microsoft.com/en-us/cpp/c-runtime-library/language-strings?view=vs-2019)

**Comment by horsicq** [comment]
Good idea. Thanks. I'll add it.
