### ISSUE TITLE
Problem getting the correct address

### ISSUE THREAD

**Issue by TheLordOfTheKings** [horsicq/stringsx64dbg#4]
Hi dear hors,
I have a silly question!
How should i calculate the address where this string used?
for example:
![string](https://user-images.githubusercontent.com/13942180/72281141-22a86900-364f-11ea-9578-fbaf16c98ae0.jpg)

Thanks alot.

**Comment by horsicq** [comment]
Hello! Make a memoryaccess breakpint on address 0x14bda61 and run debugger.

**Comment by TheLordOfTheKings** [comment]
Dear Hors,
Can you add memory on access BP to right-click menu on found strings? Maybe with an indicator that there is an active BP at this address?

**Comment by horsicq** [comment]
Thanks a lot for the good idea! I'll take a look.
