### ISSUE TITLE
Is there a way to find the string address with x64dbg?

### ISSUE THREAD

**Issue by Aholicknight** [horsicq/stringsx64dbg#5]
Here is an example:
![2vMQm0a9Rc](https://user-images.githubusercontent.com/7843719/111007254-0936a600-8354-11eb-87e0-e83b8f31553e.gif)

Is there a way to do this properly? Thank you.

**Comment by horsicq** [comment]
Hello! You should use Dump window and Memory breakpoints,

**Comment by Aholicknight** [comment]
Alright thank you

**Comment by Aholicknight** [comment]
@horsicq 
![image](https://user-images.githubusercontent.com/7843719/111041005-ac8ec600-83fb-11eb-836d-70f0bcf31d7b.png)
Which memory breakpoint would I use?

**Comment by horsicq** [comment]
Read or access
